### ISSUE TITLE
Deployment scripts include support for Secrets Provider init and standalone app containers

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-authn-k8s-client#247] opened 2021-03-17 10:51 UTC
## Is your feature request related to a problem? Please describe.

For purposes of splitting out tasks into more manageable development chunks, the demo deployment scripts that are implemented in Issue #239 do not include support for Secrets Provider init and application containers.
This issue incrementally adds support for Secrets Provider init container into those scripts.

## Out of Scope

- This issue does not include adding support for the Secrets Provider running as a standalone "app" container.
   Support for a standalone "app" container will be added with Issue #282.
- This issue will not include testing on an OpenShift platform. Testing on OpenShift will be performed in Issue #248.

## Describe the solution you would like

- Copy the summit-sidecar application deployment 
   [Helm subchart](https://github.com/cyberark/conjur-authn-k8s-client/tree/master/helm/app-deploy/charts/app-summon-sidecar) as a starting point for a new Secrets Provider init container application Helm chart.
   
- Modify the Pet-Store application manifest to mount a
   database username/password via a Kubernetes Secrets volume mount.

- Port the
  [Secrets Provider Helm chart deployment manifest](https://github.com/cyberark/secrets-provider-for-k8s/blob/master/helm/secrets-provider/templates/secrets-provider.yaml)
  as an init container for the Pet Store app manifest in the new Helm subchart.
  
  - Modify the Secrets Provider init container manifest that was created in the previous
     step as follows:
     - Replace references to the following environment variables:
        - CONJUR_APPLIANCE_URL
        - CONJUR_AUTHN_URL
        - CONJUR_ACCOUNT
        - CONJUR_SSL_CERTIFICATE
        With an `envFrom` reference to a Conjur Connect ConfigMap

  - Replace the `CONJUR_AUTHN_LOGIN` setting with either:
     - Reference to a Conjur authentication ConfigMap... OR...
     - Annotation for the authn login URL, using a Chart value for the annotation value

  - Add chart values for the following settings:

    - SECRETS_DESTINATION
    - CONTAINER_MODE
    - K8S_SECRETS
    - RETRY_INTERVAL_SEC
    - RETRY_COUNT_LIMIT
    - DEBUG

- Create a manifest for secrets that the Secrets Provider will mutate

- Mofify the scripts that were created for Issue #239 for the new Secrets Provider init container support
   as follows:
   - Modify the 0_prep_check_dependencies.sh file to require the existence of environment variable
      settings that correspond to required Secrets Provider authenticator settings in the application
      deployment Helm chart.
   - In the policy subdirectory, add Conjur policy host definitions for sample applications that use the Secrets
      Provider init or app containers.
   - Modify the `7_app_deploy.sh` to include deployment of applications using the Secrets Provider
      init container authenticator (i.e. by passing the necessary chart values to the
      application deployment Helm chart.)

  - Add any other charts values as needed to sync up the Secrets Provider subchart with other
     application deployment subcharts.

## DoD
-[ ] Summon-Sidecar application deployment subchart copied as a starting point for a Secrets Provider
      init container deployment Helm subchart (https://github.com/cyberark/conjur-authn-k8s-client/pull/299)
-[ ] Pet Store application modified so mount Kubernetes secrets for database username and password
-[ ] Secrets provider Helm chart is ported as an application deployment subchart
  -[ ] Modify the Secrets Provider init container manifest that was created in the previous
         step as follows
     -[ ] Replace references to the following environment variables with an "envFrom" reference to a Conjur Connect ConfigMap:
           - CONJUR_APPLIANCE_URL
           - CONJUR_AUTHN_URL
           - CONJUR_ACCOUNT
           - CONJUR_SSL_CERTIFICATE
     -[ ] Replace the "CONJUR_AUTHN_LOGIN" setting with either:
           - Reference to a Conjur authentication ConfigMap... OR...
           - Annotation for the authn login URL, using a Chart value for the annotation value
     -[ ] Add chart values for the following settings:
          - SECRETS_DESTINATION
          - CONTAINER_MODE
          - K8S_SECRETS
          - RETRY_INTERVAL_SEC
          - RETRY_COUNT_LIMIT
          - DEBUG
     -[ ] Create a manifest for Kubernetes Secrets that the Secrets Provider will mutate
     -[ ] Modify the scripts that were created for Issue #239 for the new Secrets Provider init container support
            as follows:
          -[ ] Modify the 0_prep_check_dependencies.sh file to require the existence of environment variable
             settings that correspond to required Secrets Provider authenticator settings in the application
             deployment Helm chart.
          -[ ] In the policy subdirectory, add Conjur policy host definitions for sample applications that use the Secrets
             Provider init or app containers.
          -[ ] Modify the `7_app_deploy.sh` to include deployment of applications using the Secrets Provider
             init container authenticator (i.e. by passing the necessary chart values to the
             application deployment Helm chart.)
  -[ ] Add any other charts values as needed to sync up the Secrets Provider subchart with other
     application deployment subcharts.
  -[ ] Scripts are tested in a Kubernetes cluster, Secrets Provider mutates Kubernetes Secrets
  -[ ] Pet Store application can use mutated Kubernetes Secrets

**Comment by izgeri** [comment] 2021-05-24 15:05
closing as duplicate of #272 and #292

**Closed by izgeri** 2021-05-24 15:05 UTC
Labels: component/k8s, kind/enhancement, triage/duplicate
