### ISSUE TITLE
E2E Workflow Scripts: Enable workflow to be run on different platforms

### ISSUE THREAD

**Issue by imheresamir** [cyberark/conjur-authn-k8s-client#321] opened 2021-06-03 08:40 UTC
## Is your feature request related to a problem? Please describe.

The E2E workflow currently only runs on Kubernetes. There should be a cleaner solution to running the workflow on OpenShift than conditional script branches specific to OpenShift scattered throughout the numbered workflow scripts.

## Describe the solution you would like

Investigate and implement modifications enabling the workflow to be run on OpenShift (or other platforms). Perhaps a `--set openshift.enabled=true` value can be set in the Helm charts to toggle between OpenShift and k8s in the spirit of the bitnami postgres chart.

**Comment by imheresamir** [comment] 2021-06-24 17:15
Possible dupe of #248

**Comment by jtuttle** [comment] 2021-08-02 15:38
Closing this out as a duplicate of #320. Originally, we were planning on removing the openshift bash logic that was copied over from the k8s-conjur-demo script, but we ended up using it as we moved onto openshift.

**Closed by jtuttle** 2021-08-02 15:38 UTC
Labels: component/k8s, kind/enhancement
